apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8node
  template:
    metadata:
      labels:
        app: my-k8node
    spec:
      containers:
      - name: my-k8node 
        image: skd93/k8node:v1
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-k8node-service
spec:
  selector:
    app: my-k8node 
  ports:
    - protocol: TCP
      port: 9091  
      targetPort: 8080
  type: NodePort